[project]
name = "moralbench"
version = "0.1.0"
description = "Package to measure the morality of LLMs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaleido>=1.2.0",
    "moralbench-api",
    "plotly>=6.5.2",
]

[tool.uv.workspace]
members = ["packages/backend"]

[tool.uv.sources]
moralbench-api = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]
